---
# Playbook to provision the server
# so that the defautl server config is totally automated

- hosts: all

  vars:
    - ssh_port: 22
    - allowed_users: demo vagrant
    - user_name: demo
    #password generation should be run on a similar machine, macOS does not create the correct value
    #python -c 'import crypt; print crypt.crypt("hello", "$1$SomeSalt$")'
    - user_password: $1$SomeSalt$L9W/KYWMIdn7AfcMZZVeU0

  # vars_files:
  #   - pathto/vars.yml

  # pre_tasks:
  #   - shell: echo 'hello'

  # roles:
  #    - server

  tasks:
    - include: 'tasks/setup_user.yml'
    - include: 'tasks/setup_ssh.yml'
    - include: 'tasks/install_csf.yml'
    - include: 'tasks/setup_firewall.yml'
    - include: 'tasks/setup_timesync.yml'



  # post_tasks:
  #   - shell: echo 'goodbye'

  handlers:
    - include: 'handlers/main.yml'
