---
# Playbook to provision the server
# so that the defautl server config is totally automated

- hosts: all

  #vars:
  # - example_var: 'value'

  # vars_files:
  #   - pathto/vars.yml

  # pre_tasks:
  #   - shell: echo 'hello'

  # roles:
  #    - server

  tasks:
    - include: 'tasks/setup_user.yml'
    - include: 'tasks/setup_ssh.yml'
    - include: 'tasks/install_csf.yml'
    - include: 'tasks/setup_firewall.yml'
    - include: 'tasks/setup_timesync.yml'

  # post_tasks:
  #   - shell: echo 'goodbye'

  handlers:
    - include: 'handlers/main.yml'
