---
# Setup CSF

- name: Setup CFS TCP ports IN {{ tcp_ports_in }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^TCP_IN =" line="TCP_IN = \"{{ tcp_ports_in }}\""
  become: yes


- name: Setup CFS TCP ports OUT {{ tcp_ports_out }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^TCP_OUT =" line="TCP_OUT = \"{{ tcp_ports_out }}\""
  become: yes


- name: Setup CFS UDP ports IN {{ udp_ports_in }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^UDP_IN =" line="UDP_IN = \"{{ udp_ports_in }}\""
  become: yes


- name: Setup CFS UDP ports OUT {{ udp_ports_out }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^UDP_IN =" line="UDP_IN = \"{{ udp_ports_out }}\""
  become: yes


- name: Allow ICMP_IN
  lineinfile: dest=/etc/csf/csf.conf regexp="^ICMP_IN =" line="ICMP_IN = \"1\""
  become: yes


- name: Disable IPV6
  lineinfile: dest=/etc/csf/csf.conf regexp="^IPV6_SPI =" line="IPV6_SPI = \"1\""
  become: yes


- name: Setup CFS TCP6 ports IN {{ tcp_ports_in }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^TCP_IN =" line="TCP_IN = \"{{ tcp_ports_in }}\""
  become: yes


- name: Setup CFS TCP6 ports OUT {{ tcp_ports_out }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^TCP_OUT =" line="TCP_OUT = \"{{ tcp_ports_out }}\""
  become: yes


- name: Setup CFS UDP6 ports IN {{ udp_ports_in }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^UDP_IN =" line="UDP_IN = \"{{ udp_ports_in }}\""
  become: yes


- name: Setup CFS UDP6 ports OUT {{ udp_ports_out }}
  lineinfile: dest=/etc/csf/csf.conf regexp="^UDP_IN =" line="UDP_IN = \"{{ udp_ports_out }}\""
  become: yes


- name: Disable TESTING
  lineinfile: dest=/etc/csf/csf.conf regexp="^TESTING =" line="TESTING = \"1\"" #TODO: switch to 0
  become: yes
  # notify:
  #   - restart csf
