---
# Applies the correct settings for SSH, including root login and disabling
# password authentication

- name: Change SSH port number
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 22" line="Port {{ ssh_port }}"
  become: yes


- name: Disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no"
  become: yes


- name: Disable root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no"
  become: yes


- name: Disable PAM use
  lineinfile: dest=/etc/ssh/sshd_config regexp="^UsePAM yes" line="UsePAM no"
  become: yes


- name: Allow default user
  lineinfile: dest=/etc/ssh/sshd_config insertafter=EOF line="AllowUsers {{ allowed_users }}"
  become: yes
  # notify:
  #   - restart ssh
