---
# Applies the correct settings for SSH, including root login and disabling
# password authentication

- name: Change SSH port number
  lineinfile: dest=/etc/ssh/sshd_config regexp="^Port 22" line="Port 22"
  become: yes


- name: Disable password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication yes" line="PasswordAuthentication no"
  become: yes


- name: Disable root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin yes" line="PermitRootLogin no"
  become: yes


- name: Disable root login secondary
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin without-password" line="PermitRootLogin no"
  become: yes


- name: Disable PAM use
  lineinfile: dest=/etc/ssh/sshd_config regexp="^UsePAM yes" line="UsePAM no"
  become: yes


- name: Allow default user
  lineinfile: dest=/etc/ssh/sshd_config insertafter=EOF line="AllowUsers demo vagrant"
  become: yes
  notify:
    - start ssh
