---
# Playbook to provision the server
# so that the defautl server config is totally automated

- hosts: all

  vars:
    - ssh_port: '22'
    - user_name: 'demo'
    - user_password: 'hello'

  # vars_files:
  #   - pathto/vars.yml

  # pre_tasks:
  #   - shell: echo 'hello'

  # roles:
  #    - server

  tasks:
    - include: 'tasks/create_user.yml'
    - include: 'tasks/setup_ssh.yml'
    # - include: 'tasks/setup_firewall.yml'

  # post_tasks:
  #   - shell: echo 'goodbye'

  handlers:
    - include: 'handlers/main.yml'
